server:
  port: 9004

spring:
  application:
    name: xdclass-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.32.9:8848
    #消息队列
  rabbitmq:
    host: 123.57.32.9
    port: 5672
    virtual-host: /
    password: password
    username: admin
    #开启⼿动确认消息
    listener:
      simple:
        acknowledge-mode: manual

  redis:
    host: 123.57.32.9
    password: 123456
    port: 8001
    #邮箱服务配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: ligang997x@163.com #发送邮件的邮箱地址
    password: SUDLFLYXWCPRSHVO #客户端授权码，不是邮箱密码,网易的是自己设置的
    from: ligang997x@163.com # 发送邮件的地址，和上面username一致

    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xdclass_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO

#阿里云OSS配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFZxPyz7mbq4oRCbbmH
    access-key-secret: Wa3rWKyJBezZdmkz44kCagWQyFXAxU
    bucketname: lee-beijing-oss

mqconfig:
  #延迟队列，不能被监听消费
  order_close_delay_queue: order.close.delay.queue
  #延迟队列的消息过期后转发的队列
  order_close_queue: order.close.queue
  #交换机
  order_event_exchange: order.event.exchange
  #进⼊延迟队列的路由key
  order_close_delay_routing_key: order.close.delay.routing.key
  #消息过期，进⼊释放死信队列的key
  order_close_routing_key: order.close.routing.key
  #消息过期时间,毫秒,测试改为15秒
  ttl: 15000

#支付宝配置
alipay:
  #支付成功的跳转页面
  success_return_url: https://xdclass.net

  #支付宝通知回调接口
  callback_url: http://xdclass.ngrok2.xiaomiqiu.cn/api/callback/order/v1/alipay